### ISSUE TITLE
Include pre-built web components resources

### ISSUE THREAD

**Issue by majick777** [elmsln/wp-plugin-hax#3]
Is all the extra installing of the web components package server-side just to try the HAX editor out in WordPress needed? 

I had troubles installing that package ([see separate issue for that](https://github.com/elmsln/wp-plugin-webcomponents/issues/3).)

I don't think many would put in the same time commitment as me just to try something out, especially in the WP ecosystem when there are lots of editor choices. 

Wouldn't it be easier to bundle the latest pre-built web component distribution script *with the WP plugin itself as a default/fallback*, and within the plugin check for the existence of built scripts in `/wp-content/webcomponents` (and use them if found) ?

**Comment by btopro** [comment]
useful feedback. We should just package the build for user experience. WP is a "and we work there" so it's been a bit of an afterthought for me personally but thank you for the feedback and I should create an internal build routine that just pushes the new assets there as well. There's a public cdn 
 that can be used for testing it that we haven't mentioned much publicly yet (till we can better support it / have more mirrors) -- https://webcomponents.psu.edu/cdn/ 

https://www.drupal.org/project/hax/issues/3050526

If your wanting to just play with it then that's the fastest route. no build, nothing.

**Comment by btopro** [comment]
So we don't ship them prebuilt because of licensing, but based on feedback the latest versions for all platforms have a CDN dropdown and default to the PSU cdn location. The directions are improved for local compiling / how to get the assets if people want to run locally (which would be recommended for production usage but isn't important to get playing with and up and going initially)
